### ISSUE TITLE
Validate all required fields

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-shared-configuration#35]
Currently only a few properties are defined as required in `schema.json` definition. This can lead to some domain having some properties while others missing them. 

- Define which properties should be present no matter what type of domain (network) we are defining.
- Refactor `schema.json` file accordingly

**Comment by MakMuftic** [comment]
@mj52951 maybe you can also look into this one, when you have some time.

**Comment by mj52951** [comment]
As I looked it up, in `schema.json` all properties, except `feeRouter` and `feeHandlers`, are already required. Also, all "inner" properties are also defined as required.

**Comment by itsbobbyzzz168** [comment]
Closed as merged
